name: Test and Deploy Shopify Theme

on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install Ruby
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Step 4: Install Bundler for Ruby dependencies
      - name: Install Bundler
        run: gem install bundler

      # Step 5: Install Ruby dependencies (for theme development, if any)
      - name: Install Ruby Dependencies
        run: bundle install
       
      # Step 6: Install Shopify CLI (for theme development)
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest @shopify/theme

      # Step 7: Install dependencies for JavaScript tests (like Jest)
      - name: Install Node.js Dependencies
        run: npm install

      # Step 8: Run Unit Tests
      - name: Run Tests
        run: npm test # Change this to your test command (e.g., jest or mocha)

      # Step 9: Conditional Deploy after successful tests
      - name: Deploy Theme to Shopify
        if: success()  # Only deploy if tests pass
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
